project:
  type: website
  output-dir: D:\E-Portfolio

website:
  title: "E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: content.qmd
        text: Content & Deliverables
      - href: Publications.qmd
        text: Publications

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

